"""new_initial_migration7

Revision ID: f76e854d2b2a
Revises: 
Create Date: 2024-12-31 16:53:36.651236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76e854d2b2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('productionYear', sa.Integer(), nullable=False),
    sa.Column('licensePlate', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licensePlate')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_table('garages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garages_id'), 'garages', ['id'], unique=False)
    op.create_table('car_garages',
    sa.Column('carId', sa.Integer(), nullable=False),
    sa.Column('garageId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carId'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garageId'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('carId', 'garageId')
    )
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carId', sa.Integer(), nullable=False),
    sa.Column('serviceType', sa.String(length=200), nullable=False),
    sa.Column('scheduledDate', sa.Date(), nullable=False),
    sa.Column('garageId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carId'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['garageId'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_table('car_garages')
    op.drop_index(op.f('ix_garages_id'), table_name='garages')
    op.drop_table('garages')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
